In [1]:
import numpy as np
from scipy.sparse import coo_matrix, vstack

In [2]:
import cv2
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from matplotlib import pyplot as plt
import numpy as np 
from glob import glob
import pickle
import multiprocessing
import os

In [3]:
random_feats = "/home/ubuntu/foodissues_feats_randomsample/all.feat"

In [4]:
x = np.loadtxt(random_feats, delimiter=',')

In [5]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [6]:
x_norm = scaler.transform(x)

In [7]:
import pickle

In [8]:
pickle.dump(scaler, open("scaler1.pkl", 'wb'))

In [9]:
from sklearn.decomposition import PCA

pca = PCA(random_state=9037293)
pca.fit(x_norm)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=9037293,
  svd_solver='auto', tol=0.0, whiten=False)

In [10]:
pickle.dump(pca, open("pca1.pkl", 'wb'))

In [11]:
x_norm_pca = pca.transform(x_norm)

In [12]:
from sklearn.cluster import KMeans
model = KMeans(n_clusters=100, random_state=9037293, n_jobs=4, n_init=1, max_iter=200, verbose=2)
model.fit(x_norm_pca)

Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 14822777.809971621
start iteration
done sorting
end inner loop
Iteration 1, inertia 14152131.232334724
start iteration
done sorting
end inner loop
Iteration 2, inertia 13986407.251814773
start iteration
done sorting
end inner loop
Iteration 3, inertia 13906275.904987143
start iteration
done sorting
end inner loop
Iteration 4, inertia 13856220.667717647
start iteration
done sorting
end inner loop
Iteration 5, inertia 13819394.775958123
start iteration
done sorting
end inner loop
Iteration 6, inertia 13790188.865358109
start iteration
done sorting
end inner loop
Iteration 7, inertia 13766833.756234013
start iteration
done sorting
end inner loop
Iteration 8, inertia 13748853.263869047
start iteration
done sorting
end inner loop
Iteration 9, inertia 13734341.334182043
start iteration
done sorting
end inner loop
Iteration 10, inertia 13722165.309542293
start iteration
done sorting
end inner loop
Iterati

Iteration 96, inertia 13618269.421949856
start iteration
done sorting
end inner loop
Iteration 97, inertia 13618219.244171102
start iteration
done sorting
end inner loop
Iteration 98, inertia 13618170.128088152
start iteration
done sorting
end inner loop
Iteration 99, inertia 13618122.03554546
start iteration
done sorting
end inner loop
Iteration 100, inertia 13618081.653523743
start iteration
done sorting
end inner loop
Iteration 101, inertia 13618041.532158209
start iteration
done sorting
end inner loop
Iteration 102, inertia 13618013.53669511
start iteration
done sorting
end inner loop
Iteration 103, inertia 13617984.03083132
start iteration
done sorting
end inner loop
Iteration 104, inertia 13617957.141871966
start iteration
done sorting
end inner loop
Iteration 105, inertia 13617930.673387228
start iteration
done sorting
end inner loop
Iteration 106, inertia 13617905.783515744
start iteration
done sorting
end inner loop
Iteration 107, inertia 13617877.863150971
start iteration
don

done sorting
end inner loop
Iteration 192, inertia 13616186.119263837
start iteration
done sorting
end inner loop
Iteration 193, inertia 13616182.81913198
start iteration
done sorting
end inner loop
Iteration 194, inertia 13616180.470809765
start iteration
done sorting
end inner loop
Iteration 195, inertia 13616177.994029913
start iteration
done sorting
end inner loop
Iteration 196, inertia 13616175.948866308
start iteration
done sorting
end inner loop
Iteration 197, inertia 13616174.849440053
start iteration
done sorting
end inner loop
Iteration 198, inertia 13616172.623052001
start iteration
done sorting
end inner loop
Iteration 199, inertia 13616170.859283857


KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=200,
    n_clusters=100, n_init=1, n_jobs=4, precompute_distances='auto',
    random_state=9037293, tol=0.0001, verbose=2)

In [13]:
pickle.dump(model, open("kmeans1.pkl", 'wb'))

In [14]:
model.cluster_centers_.shape

(100, 128)

In [15]:
model.cluster_centers_

array([[-2.80585616e+00,  3.99912764e+00,  1.95848673e-02, ...,
        -1.64151791e-02, -2.24137809e-02,  1.88495088e-02],
       [ 3.57084370e+00,  1.25995038e+00, -3.18467032e+00, ...,
         7.61586162e-02, -1.49454943e-02,  1.79444482e-02],
       [-4.70191744e+00,  1.91140265e-01, -5.90274952e-01, ...,
        -3.73037049e-02,  5.78330410e-03, -1.88466270e-02],
       ...,
       [-1.69225348e+00, -7.83604523e-01,  5.14904208e-01, ...,
        -2.18813489e-03, -1.64760538e-03, -1.65653127e-03],
       [-2.67872898e+00,  3.11916379e+00, -2.31873653e+00, ...,
        -1.31001956e-02,  8.16616111e-03, -1.13569572e-02],
       [ 1.24398020e+00, -3.07126953e+00, -1.62280125e+00, ...,
         5.60648409e-03, -2.26702809e-03, -2.61553654e-04]])

In [16]:
sample = "/home/ubuntu/foodissues_features/3217.feat"
x1 = np.loadtxt(sample, delimiter=',')

In [17]:
x1_norm = scaler.transform(x1)
x1_norm_pca = pca.transform(x1_norm)
x1_pred = model.predict(x1_norm_pca)

In [24]:
x1_pred

array([78, 75, 75, ..., 43, 24, 63], dtype=int32)

In [26]:
x1_pred_hist = np.zeros(100)
for v in x1_pred:
    x1_pred_hist[v] += 1
x1_pred_hist/x1_pred_hist.sum()

array([0.01609862, 0.01276287, 0.00203046, 0.02480058, 0.00942712,
       0.00638144, 0.00609137, 0.01783901, 0.0271211 , 0.00145033,
       0.00290065, 0.00855693, 0.00551124, 0.00464104, 0.00812183,
       0.02291516, 0.0062364 , 0.00913706, 0.00362582, 0.00217549,
       0.00275562, 0.00899202, 0.00739666, 0.01609862, 0.07947788,
       0.00348078, 0.00913706, 0.00391588, 0.00507614, 0.00391588,
       0.00536621, 0.00580131, 0.00565627, 0.0075417 , 0.00725163,
       0.00536621, 0.00681653, 0.00261059, 0.00029007, 0.00435098,
       0.03277737, 0.00101523, 0.00493111, 0.02987672, 0.00797679,
       0.00536621, 0.01145758, 0.00145033, 0.00420595, 0.00783176,
       0.01827411, 0.01392313, 0.0066715 , 0.01493836, 0.02654097,
       0.00768673, 0.00362582, 0.01479333, 0.00377085, 0.00435098,
       0.00377085, 0.01189268, 0.00449601, 0.00391588, 0.00478608,
       0.00232052, 0.00449601, 0.00217549, 0.01754895, 0.01102248,
       0.00188542, 0.02102973, 0.00478608, 0.01624365, 0.00362

In [29]:
def get_vbow(sample_path, scaler, pca, model):
    x1 = np.loadtxt(sample_path, delimiter=',')
    x1_norm = scaler.transform(x1)
    x1_norm_pca = pca.transform(x1_norm)
    x1_pred = model.predict(x1_norm_pca)
    x1_pred_hist = np.zeros(100)
    for v in x1_pred:
        x1_pred_hist[v] += 1
    x1_pred_hist /= x1_pred_hist.sum()
    name = os.path.basename(sample_path).strip(".feat")
    np.savetxt("/home/ubuntu/foodissues_vbow/" + name + ".vbow", x1_pred_hist, delimiter = ',')

In [32]:
sift_dir = "/home/ubuntu/foodissues_features/"
sift_list = glob(sift_dir + "/*")

count = 0
for s in sift_list:
    name = os.path.basename(s).strip(".feat")
    if not os.path.exists("/home/ubuntu/foodissues_vbow/" + name + ".vbow"):
        try:
            get_vbow(s, scaler, pca, model)
            count += 1
        except:
            pass
    else:
        count += 1
    if count % 50 == 0:
        print(count)

50
100
150
200
250
300
350
400
450
500
550
600
650
700
750
800
850
900
950
1000
1050
1100
1150
1200


/home/ubuntu/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: UserWarning: loadtxt: Empty input file: "/home/ubuntu/foodissues_features/1214.feat"
  


1250
1300
1350


/home/ubuntu/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: UserWarning: loadtxt: Empty input file: "/home/ubuntu/foodissues_features/1222.feat"
  


1400
1450
1500
1550
1600
1650
1700
1750
1800
1850
1900
1950
2000
2050
2100
2150
2200
2250
2300
2350
2400
2450
2500
2550


In [35]:
vbow_dir = "/home/ubuntu/foodissues_vbow/"
vbow_list = glob(vbow_dir + "/*")
names = []
vbow_fts = np.empty((0,100))
for v in vbow_list:
    vbow = np.array(open(v).read().splitlines()).reshape((1,100))
    name = os.path.basename(v).strip('.vbow')
    names.append(name)
    vbow_fts = np.r_[vbow_fts, vbow]

In [43]:
from sklearn.neighbors import NearestNeighbors as KNN

In [44]:
neigh = KNN(n_neighbors=10)

In [45]:
neigh.fit(vbow_fts)

NearestNeighbors(algorithm='auto', leaf_size=30, metric='minkowski',
         metric_params=None, n_jobs=1, n_neighbors=10, p=2, radius=1.0)

In [49]:
nbrs = neigh.kneighbors(vbow_fts, 10, False)

In [53]:
nbrs[:5] + 1

array([[1392,    1,  423,   47, 1572, 1710,  902,  676,  545,  551],
       [   2, 1009, 2361,  325, 1351, 1947, 2403, 1081, 1005, 1916],
       [ 945,  765, 2231,    3,  268,   70,  747, 2482, 2330,  571],
       [   4,  864,  908, 2350, 1621, 1116, 1861, 1347, 2144, 1857],
       [   5, 1897, 1886, 1722, 1942,  731, 1247,  800,  206, 1154]])

In [56]:
names = np.array(names, dtype='int')

In [57]:
names[:5]

array([4056,  523, 3658, 4123, 1548])

In [58]:
names[nbrs[0]+1]

array([1203,  523, 4168, 3944, 2704,    8, 3191, 3203, 4263, 4558])